# Generated by Django 5.2.14 on 2026-05-27 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(help_text='Internal value for matching', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_value', models.CharField(blank=True, help_text='Matches Step 1', max_length=50)),
                ('vibe_value', models.CharField(blank=True, help_text='Matches Step 2', max_length=50)),
                ('occasion_value', models.CharField(blank=True, help_text='Matches Step 3', max_length=50)),
                ('season_value', models.CharField(blank=True, help_text='Matches Step 4', max_length=50)),
                ('strength_value', models.CharField(blank=True, help_text='Matches Step 5', max_length=50)),
                ('score_weight', models.PositiveIntegerField(default=1, help_text='Higher = stronger match')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_recommendations', to='shop.product')),
            ],
        ),
    ]
