# Generated by Django 5.2.14 on 2026-05-27 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#D4AF37', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BottleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('hex_color', models.CharField(default='#000000', max_length=7)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='bottles/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BottleSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_ml', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FragranceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, default='🌸', help_text='Emoji icon', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notes/')),
                ('category', models.CharField(choices=[('top', 'Top Note'), ('middle', 'Middle Note'), ('base', 'Base Note')], default='top', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Longevity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('hours', models.PositiveIntegerField(default=4, help_text='Minimum hours')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Longevities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MoodCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('color', models.CharField(default='#D4AF37', help_text='Theme color hex', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='moods/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OccasionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TravelLuxScents', max_length=100)),
                ('tagline', models.CharField(default='Premium Fragrance Decants', max_length=200)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('free_delivery_text', models.CharField(default='Free Delivery Over £40', max_length=200)),
                ('whatsapp_number', models.CharField(default='+447000000000', max_length=20)),
                ('whatsapp_message', models.CharField(default='Hi! I need help with my order.', max_length=300)),
                ('footer_disclaimer', models.TextField(default='This product is independently decanted and re-bottled. We are not affiliated with the original brand.')),
                ('account_benefits_text', models.TextField(default='Track your orders, get personalised recommendations, and enjoy faster checkout.')),
                ('currency_symbol', models.CharField(default='£', max_length=5)),
                ('delivery_info', models.TextField(default='Royal Mail 1st Class • 1-2 Business Days')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(default='✓', help_text='Emoji or icon class', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_hover', models.ImageField(blank=True, help_text='GIF or second image for hover', null=True, upload_to='products/hover/')),
                ('video_preview', models.FileField(blank=True, null=True, upload_to='products/videos/')),
                ('in_stock', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('badges', models.ManyToManyField(blank=True, related_name='products', to='shop.badge')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.gender')),
                ('longevity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.longevity')),
                ('mood_collections', models.ManyToManyField(blank=True, related_name='products', to='shop.moodcollection')),
                ('notes', models.ManyToManyField(blank=True, related_name='products', to='shop.fragrancenote')),
                ('occasions', models.ManyToManyField(blank=True, related_name='products', to='shop.occasiontag')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoverySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('pick_count', models.PositiveIntegerField(help_text='Number of items to pick (e.g. 3, 5, 10)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Shown as strikethrough', max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='discovery/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('bottle_size', models.ForeignKey(help_text='Bottle size for this set', on_delete=django.db.models.deletion.CASCADE, to='shop.bottlesize')),
                ('excluded_products', models.ManyToManyField(blank=True, related_name='excluded_discovery_sets', to='shop.product')),
                ('included_products', models.ManyToManyField(blank=True, help_text='Leave blank for all products', related_name='discovery_sets', to='shop.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_quantity', models.PositiveIntegerField(default=10)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='variants/')),
                ('bottle_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.bottlecolor')),
                ('bottle_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.bottlesize')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'ordering': ['bottle_size__order', 'bottle_color__order'],
                'unique_together': {('product', 'bottle_size', 'bottle_color')},
            },
        ),
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='shop.product')),
            ],
            options={
                'unique_together': {('product', 'email')},
            },
        ),
    ]
