# Generated by Django 5.2.14 on 2026-05-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="TravelLuxeScent", max_length=100),
        ),
    ]
